// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"rinha/models"
)

// ConsultarExtratoOKCode is the HTTP code returned for type ConsultarExtratoOK
const ConsultarExtratoOKCode int = 200

/*
ConsultarExtratoOK OK

swagger:response consultarExtratoOK
*/
type ConsultarExtratoOK struct {

	/*
	  In: Body
	*/
	Payload *models.Extrato `json:"body,omitempty"`
}

// NewConsultarExtratoOK creates ConsultarExtratoOK with default headers values
func NewConsultarExtratoOK() *ConsultarExtratoOK {

	return &ConsultarExtratoOK{}
}

// WithPayload adds the payload to the consultar extrato o k response
func (o *ConsultarExtratoOK) WithPayload(payload *models.Extrato) *ConsultarExtratoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the consultar extrato o k response
func (o *ConsultarExtratoOK) SetPayload(payload *models.Extrato) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConsultarExtratoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ConsultarExtratoNotFoundCode is the HTTP code returned for type ConsultarExtratoNotFound
const ConsultarExtratoNotFoundCode int = 404

/*
ConsultarExtratoNotFound Not Found

swagger:response consultarExtratoNotFound
*/
type ConsultarExtratoNotFound struct {
}

// NewConsultarExtratoNotFound creates ConsultarExtratoNotFound with default headers values
func NewConsultarExtratoNotFound() *ConsultarExtratoNotFound {

	return &ConsultarExtratoNotFound{}
}

// WriteResponse to the client
func (o *ConsultarExtratoNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// ConsultarExtratoInternalServerErrorCode is the HTTP code returned for type ConsultarExtratoInternalServerError
const ConsultarExtratoInternalServerErrorCode int = 500

/*
ConsultarExtratoInternalServerError Internal Server Error

swagger:response consultarExtratoInternalServerError
*/
type ConsultarExtratoInternalServerError struct {
}

// NewConsultarExtratoInternalServerError creates ConsultarExtratoInternalServerError with default headers values
func NewConsultarExtratoInternalServerError() *ConsultarExtratoInternalServerError {

	return &ConsultarExtratoInternalServerError{}
}

// WriteResponse to the client
func (o *ConsultarExtratoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
