// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"rinha/models"
)

// RealizarTransacaoOKCode is the HTTP code returned for type RealizarTransacaoOK
const RealizarTransacaoOKCode int = 200

/*
RealizarTransacaoOK OK

swagger:response realizarTransacaoOK
*/
type RealizarTransacaoOK struct {

	/*
	  In: Body
	*/
	Payload *models.TransacaoOutput `json:"body,omitempty"`
}

// NewRealizarTransacaoOK creates RealizarTransacaoOK with default headers values
func NewRealizarTransacaoOK() *RealizarTransacaoOK {

	return &RealizarTransacaoOK{}
}

// WithPayload adds the payload to the realizar transacao o k response
func (o *RealizarTransacaoOK) WithPayload(payload *models.TransacaoOutput) *RealizarTransacaoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the realizar transacao o k response
func (o *RealizarTransacaoOK) SetPayload(payload *models.TransacaoOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RealizarTransacaoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RealizarTransacaoNotFoundCode is the HTTP code returned for type RealizarTransacaoNotFound
const RealizarTransacaoNotFoundCode int = 404

/*
RealizarTransacaoNotFound Not Found

swagger:response realizarTransacaoNotFound
*/
type RealizarTransacaoNotFound struct {
}

// NewRealizarTransacaoNotFound creates RealizarTransacaoNotFound with default headers values
func NewRealizarTransacaoNotFound() *RealizarTransacaoNotFound {

	return &RealizarTransacaoNotFound{}
}

// WriteResponse to the client
func (o *RealizarTransacaoNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// RealizarTransacaoUnprocessableEntityCode is the HTTP code returned for type RealizarTransacaoUnprocessableEntity
const RealizarTransacaoUnprocessableEntityCode int = 422

/*
RealizarTransacaoUnprocessableEntity Bad Request

swagger:response realizarTransacaoUnprocessableEntity
*/
type RealizarTransacaoUnprocessableEntity struct {
}

// NewRealizarTransacaoUnprocessableEntity creates RealizarTransacaoUnprocessableEntity with default headers values
func NewRealizarTransacaoUnprocessableEntity() *RealizarTransacaoUnprocessableEntity {

	return &RealizarTransacaoUnprocessableEntity{}
}

// WriteResponse to the client
func (o *RealizarTransacaoUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}

// RealizarTransacaoInternalServerErrorCode is the HTTP code returned for type RealizarTransacaoInternalServerError
const RealizarTransacaoInternalServerErrorCode int = 500

/*
RealizarTransacaoInternalServerError Internal Server Error

swagger:response realizarTransacaoInternalServerError
*/
type RealizarTransacaoInternalServerError struct {
}

// NewRealizarTransacaoInternalServerError creates RealizarTransacaoInternalServerError with default headers values
func NewRealizarTransacaoInternalServerError() *RealizarTransacaoInternalServerError {

	return &RealizarTransacaoInternalServerError{}
}

// WriteResponse to the client
func (o *RealizarTransacaoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
