// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RealizarTransacaoHandlerFunc turns a function with the right signature into a realizar transacao handler
type RealizarTransacaoHandlerFunc func(RealizarTransacaoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RealizarTransacaoHandlerFunc) Handle(params RealizarTransacaoParams) middleware.Responder {
	return fn(params)
}

// RealizarTransacaoHandler interface for that can handle valid realizar transacao params
type RealizarTransacaoHandler interface {
	Handle(RealizarTransacaoParams) middleware.Responder
}

// NewRealizarTransacao creates a new http.Handler for the realizar transacao operation
func NewRealizarTransacao(ctx *middleware.Context, handler RealizarTransacaoHandler) *RealizarTransacao {
	return &RealizarTransacao{Context: ctx, Handler: handler}
}

/*
	RealizarTransacao swagger:route POST /clientes/{id}/transacoes realizarTransacao

# Realizar transação

Realizar transação
*/
type RealizarTransacao struct {
	Context *middleware.Context
	Handler RealizarTransacaoHandler
}

func (o *RealizarTransacao) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRealizarTransacaoParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
