// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Rinha",
    "version": "0.1.0"
  },
  "paths": {
    "/clientes/{id}/extrato": {
      "get": {
        "description": "Consultar extrato",
        "summary": "Consultar extrato",
        "operationId": "consultarExtrato",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Extrato"
            }
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/clientes/{id}/transacoes": {
      "post": {
        "description": "Realizar transação",
        "summary": "Realizar transação",
        "operationId": "realizarTransacao",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TransacaoInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/TransacaoOutput"
            }
          },
          "404": {
            "description": "Not Found"
          },
          "422": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  },
  "definitions": {
    "Extrato": {
      "type": "object",
      "required": [
        "saldo",
        "ultimas_transacoes"
      ],
      "properties": {
        "saldo": {
          "type": "object",
          "$ref": "#/definitions/SaldoExtrato"
        },
        "ultimas_transacoes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ListaExtrato"
          }
        }
      }
    },
    "ListaExtrato": {
      "type": "object",
      "required": [
        "valor",
        "descricao",
        "tipo",
        "realizada_em"
      ],
      "properties": {
        "descricao": {
          "type": "string"
        },
        "realizada_em": {
          "type": "string",
          "format": "date-time"
        },
        "tipo": {
          "type": "string",
          "enum": [
            "c",
            "d"
          ]
        },
        "valor": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "SaldoExtrato": {
      "type": "object",
      "required": [
        "total",
        "data_extrato",
        "limite"
      ],
      "properties": {
        "data_extrato": {
          "type": "string",
          "format": "date-time"
        },
        "limite": {
          "type": "integer",
          "format": "int64"
        },
        "total": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "TransacaoInput": {
      "type": "object",
      "required": [
        "valor",
        "descricao",
        "tipo"
      ],
      "properties": {
        "descricao": {
          "type": "string",
          "maxLength": 10,
          "minLength": 1
        },
        "tipo": {
          "type": "string",
          "enum": [
            "c",
            "d"
          ]
        },
        "valor": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "TransacaoOutput": {
      "type": "object",
      "required": [
        "limite",
        "saldo"
      ],
      "properties": {
        "limite": {
          "type": "integer",
          "format": "int64"
        },
        "saldo": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Rinha",
    "version": "0.1.0"
  },
  "paths": {
    "/clientes/{id}/extrato": {
      "get": {
        "description": "Consultar extrato",
        "summary": "Consultar extrato",
        "operationId": "consultarExtrato",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Extrato"
            }
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/clientes/{id}/transacoes": {
      "post": {
        "description": "Realizar transação",
        "summary": "Realizar transação",
        "operationId": "realizarTransacao",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TransacaoInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/TransacaoOutput"
            }
          },
          "404": {
            "description": "Not Found"
          },
          "422": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  },
  "definitions": {
    "Extrato": {
      "type": "object",
      "required": [
        "saldo",
        "ultimas_transacoes"
      ],
      "properties": {
        "saldo": {
          "type": "object",
          "$ref": "#/definitions/SaldoExtrato"
        },
        "ultimas_transacoes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ListaExtrato"
          }
        }
      }
    },
    "ListaExtrato": {
      "type": "object",
      "required": [
        "valor",
        "descricao",
        "tipo",
        "realizada_em"
      ],
      "properties": {
        "descricao": {
          "type": "string"
        },
        "realizada_em": {
          "type": "string",
          "format": "date-time"
        },
        "tipo": {
          "type": "string",
          "enum": [
            "c",
            "d"
          ]
        },
        "valor": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "SaldoExtrato": {
      "type": "object",
      "required": [
        "total",
        "data_extrato",
        "limite"
      ],
      "properties": {
        "data_extrato": {
          "type": "string",
          "format": "date-time"
        },
        "limite": {
          "type": "integer",
          "format": "int64"
        },
        "total": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "TransacaoInput": {
      "type": "object",
      "required": [
        "valor",
        "descricao",
        "tipo"
      ],
      "properties": {
        "descricao": {
          "type": "string",
          "maxLength": 10,
          "minLength": 1
        },
        "tipo": {
          "type": "string",
          "enum": [
            "c",
            "d"
          ]
        },
        "valor": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "TransacaoOutput": {
      "type": "object",
      "required": [
        "limite",
        "saldo"
      ],
      "properties": {
        "limite": {
          "type": "integer",
          "format": "int64"
        },
        "saldo": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  }
}`))
}
