// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DadosBancario struct {
	IDConta     int32
	Limite      int64
	NomeCliente string
}

type Saldo struct {
	IDConta int32
	Saldo   int64
}

type Transaco struct {
	ID           int64
	IDConta      int32
	TipoOperacao interface{}
	Valor        int64
	Descricao    string
	CreatedAt    pgtype.Timestamp
}
