// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Extrato extrato
//
// swagger:model Extrato
type Extrato struct {

	// saldo
	// Required: true
	Saldo *SaldoExtrato `json:"saldo"`

	// ultimas transacoes
	// Required: true
	UltimasTransacoes []*ListaExtrato `json:"ultimas_transacoes"`
}

// Validate validates this extrato
func (m *Extrato) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSaldo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUltimasTransacoes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Extrato) validateSaldo(formats strfmt.Registry) error {

	if err := validate.Required("saldo", "body", m.Saldo); err != nil {
		return err
	}

	if m.Saldo != nil {
		if err := m.Saldo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("saldo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("saldo")
			}
			return err
		}
	}

	return nil
}

func (m *Extrato) validateUltimasTransacoes(formats strfmt.Registry) error {

	if err := validate.Required("ultimas_transacoes", "body", m.UltimasTransacoes); err != nil {
		return err
	}

	for i := 0; i < len(m.UltimasTransacoes); i++ {
		if swag.IsZero(m.UltimasTransacoes[i]) { // not required
			continue
		}

		if m.UltimasTransacoes[i] != nil {
			if err := m.UltimasTransacoes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ultimas_transacoes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ultimas_transacoes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this extrato based on the context it is used
func (m *Extrato) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSaldo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUltimasTransacoes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Extrato) contextValidateSaldo(ctx context.Context, formats strfmt.Registry) error {

	if m.Saldo != nil {

		if err := m.Saldo.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("saldo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("saldo")
			}
			return err
		}
	}

	return nil
}

func (m *Extrato) contextValidateUltimasTransacoes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.UltimasTransacoes); i++ {

		if m.UltimasTransacoes[i] != nil {

			if swag.IsZero(m.UltimasTransacoes[i]) { // not required
				return nil
			}

			if err := m.UltimasTransacoes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ultimas_transacoes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ultimas_transacoes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Extrato) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Extrato) UnmarshalBinary(b []byte) error {
	var res Extrato
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
